name: Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get base commit
        id: base-commit
        run: |
          # Get all release tags sorted by version
          PREV_TAG=$(git tag -l 'v*' | sort -V | grep -v $(git describe --tags --abbrev=0) | tail -n 1)
          if [ -z "$PREV_TAG" ]; then
            # First release - compare with first commit
            BASE=$(git rev-list --max-parents=0 HEAD)
            echo "First release, using initial commit as base"
          else
            # Use previous release tag
            BASE=$PREV_TAG
            echo "Found previous release tag: $PREV_TAG"
          fi
          echo "Using base: $BASE"
          echo "base=$BASE" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@jameshusband'

      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize Nx Cloud
        run: npx nx connect-to-nx-cloud

      - name: Build affected packages
        run: npx nx affected --target=build --base=${{ steps.base-commit.outputs.base }}

      - name: Get affected packages
        id: affected-packages
        run: |
          # Get affected projects
          AFFECTED=$(npx nx show projects --affected --base=${{ steps.base-commit.outputs.base }} --json)
          echo "Found affected projects: $AFFECTED"
          
          # Extract package directories and convert to JSON array
          PACKAGES_JSON=$(echo "$AFFECTED" | jq -c '[.[] | select(startswith("HelloWorld") or startswith("PingPong")) | if startswith("HelloWorld") then "packages/helloWorld" else "packages/ping-pong" end]')
          echo "Final packages list: $PACKAGES_JSON"
          echo "packages=$PACKAGES_JSON" >> $GITHUB_OUTPUT

      - name: Check and publish packages
        if: steps.affected-packages.outputs.packages != '[]'
        run: |
          # Get the release version from the tag (e.g., v1.2.3 -> 1.2.3)
          RELEASE_VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          
          for dir in $(echo '${{ steps.affected-packages.outputs.packages }}' | jq -r '.[]'); do
            if [ -f "$dir/package.json" ]; then
              cd $dir
              
              # Get current version from package.json
              CURRENT_VERSION=$(node -p "require('./package.json').version")
              
              # Check if package has changed
              if git diff --quiet ${{ steps.base-commit.outputs.base }} HEAD -- .; then
                echo "No changes in $dir since last release"
                cd -
                continue
              fi
              
              # Update version and publish
              echo "Publishing $dir with version $RELEASE_VERSION"
              npm version $RELEASE_VERSION --no-git-tag-version
              npm pkg set "publishConfig.@JamesHusband:registry"="https://npm.pkg.github.com"
              npm publish --access public
              cd -
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 