name: Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@JamesHusband'

      # Update package-lock.json first
      - name: Install dependencies and update lock file
        run: |
          npm install
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package-lock.json
          git commit -m "chore: update package-lock.json" || echo "No changes to commit"

      - name: Build all packages
        run: npx nx run-many --target=build --all

      - name: Get package directories
        id: pkg-dirs
        run: |
          DIRS=$(find packages -maxdepth 1 -mindepth 1 -type d | jq -R -s -c 'split("\n")[:-1]')
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT

      - name: Publish packages
        run: |
          for dir in $(echo '${{ steps.pkg-dirs.outputs.dirs }}' | jq -r '.[]'); do
            if [ -f "$dir/package.json" ]; then
              cd $dir
              # Update package name to include GitHub organization scope
              npm pkg set name="@JamesHusband/$(npm pkg get name | tr -d '"')"
              # Ensure correct publishConfig
              npm pkg set "publishConfig.@JamesHusband:registry"="https://npm.pkg.github.com"
              npm publish --access public
              cd -
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 